name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: dmego/waka-readme-stats@gitconfig
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_LOC_CHART: "False"
          LOCALE: "zh"
